version: "3"
services:
  fs-example:
    build:
      context: fs-example
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - ./fs-example:/usr/src/app

  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
    - ./:/usr/src/app/
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - default
