version: "3"
services:
  app:
    build: .
    ports:
      - "80:8080"
    volumes:
    - ./server/public/output/:/usr/src/app/server/public/output/
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome
    expose:
      - "4444"
    networks:
      - default