version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    volumes:
    - ./:/usr/src/app/
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome
    expose:
      - "4444"
    networks:
      - default
